{
 "title": "Cluster Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Slurm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slurmctld",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurmctld/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Slurmd",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurmd/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Watchers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "SQS-Watcher Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /sqswatcher/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Node Watcher Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /nodewatcher/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "JOB Watcher Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /jobwatcher/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Init", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "cfn-init",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /cfn-init/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "cloud-init",
   "type": "logs",
   "gridPos": { "h": 13, "w": 11, "x": 12, "y": 30 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /cloud-init/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Supervisord",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /supervisord/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "System Messages",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /system-messages/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "DCV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "DCV Authenticator Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /dcv-authenticator/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DCV Server Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /dcv-server/",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Aggregate Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Cluster Logs (ALL)",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message \n| sort @timestamp desc\n| limit 20",
     "logGroupNames": [ "/aws/parallelcluster/grafana2" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}