{
 "title": "RES Node Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{instance_name=\"RES\"}, nodename)"
   },
   {
    "name": "node_instance_id",
    "query": "label_values(node_uname_info{nodename=\"$node\"}, instance_id)"
   },
   {
    "name": "maxmount",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_size_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance_id=\"$node_instance_id\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id=\"$node_instance_id\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance_id=\"$node_instance_id\"} / (node_memory_MemTotal_bytes{instance_id=\"$node_instance_id\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance_id=\"$node_instance_id\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance_id=\"$node_instance_id\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "((1 - (node_memory_SwapFree_bytes{instance_id=\"$node_instance_id\"} / node_memory_SwapTotal_bytes{instance_id=\"$node_instance_id\"})) * 100) or on() vector(0)",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance_id=\"$node_instance_id\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance_id=\"$node_instance_id\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance_id=\"$node_instance_id\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance_id=\"$node_instance_id\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=\"$node_instance_id\"} - node_memory_MemAvailable_bytes{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance_id=\"$node_instance_id\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance_id=\"$node_instance_id\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance_id=\"$node_instance_id\"}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Read/write completions per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance_id=\"$node_instance_id\"}[30m]) / irate(node_disk_reads_completed_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance_id=\"$node_instance_id\"}[30m]) / irate(node_disk_writes_completed_total{instance_id=\"$node_instance_id\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "EFA / InfiniBand (populates if EFA hardware present)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 999 }
  },
  {
   "title": "EFA Bandwidth (RX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1000 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_amazonefa_rx_bytes{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} RX"
    }
   ]
  },
  {
   "title": "EFA Bandwidth (TX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1000 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_amazonefa_tx_bytes{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} TX"
    }
   ]
  },
  {
   "title": "EFA Packet Rate (RX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1008 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_rx_pkts{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} RX"
    }
   ]
  },
  {
   "title": "EFA Packet Rate (TX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1008 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_tx_pkts{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} TX"
    }
   ]
  },
  {
   "title": "EFA RDMA Read Throughput",
   "type": "timeseries",
   "description": "RDMA read bytes/s from EFA hw_counters (node_amazonefa_rdma_read_bytes). Populated by the efa-metrics.sh textfile collector on EFA-capable instances.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1016 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_amazonefa_rdma_read_bytes{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} RDMA read"
    }
   ]
  },
  {
   "title": "EFA RDMA Write Throughput",
   "type": "timeseries",
   "description": "RDMA write bytes/s from EFA hw_counters (node_amazonefa_rdma_write_bytes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1016 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_amazonefa_rdma_write_bytes{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} RDMA write"
    }
   ]
  },
  {
   "title": "EFA SRD Retransmitted Packets",
   "type": "timeseries",
   "description": "EFA Scalable Reliable Datagram retransmissions/s (node_amazonefa_retrans_pkts). Sustained non-zero values indicate fabric packet loss or congestion — the closest EFA equivalent of a 'dropped packet' signal.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1024 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_retrans_pkts{instance_id=\"$node_instance_id\"}[1m])",
     "legendFormat": "{{device}} port {{port}} retrans"
    }
   ]
  },
  {
   "title": "EFA Work-Request Errors",
   "type": "timeseries",
   "description": "RDMA read/write work-request error rate from EFA hw_counters (node_amazonefa_rdma_read_wr_err + rdma_write_wr_err). Should normally be flat at zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1024 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_rdma_read_wr_err{instance_id=\"$node_instance_id\"}[5m])",
     "legendFormat": "{{device}} port {{port}} read WR err"
    },
    {
     "expr": "rate(node_amazonefa_rdma_write_wr_err{instance_id=\"$node_instance_id\"}[5m])",
     "legendFormat": "{{device}} port {{port}} write WR err"
    }
   ]
  }
 ]
}